<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>Enhanced text</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>__以下</string>
			<key>match</key>
			<string>^\_\_(\s|\_|.)*</string>
			<key>name</key>
			<string>meta.package</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>--以下</string>
			<key>match</key>
			<string>^\-\-(\s|\-|.)*</string>
			<key>name</key>
			<string>entity.name.type</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>#と数字、ドット、ハイフン</string>
			<key>match</key>
			<string>#(\d|\-|\.)+</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>行頭の&gt;以下</string>
			<key>match</key>
			<string>^\&gt;.*</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>行頭の+か-</string>
			<key>match</key>
			<string>(^|\s)((\+|\-)|・)</string>
			<key>name</key>
			<string>keyword.control.import</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>カッコ内の数字</string>
			<key>match</key>
			<string>(^|\s)\((\d|\.|\-)+\)</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>[]内の文字</string>
			<key>match</key>
			<string>(^|\s)\[.+\]</string>
			<key>name</key>
			<string>keyword.control.import</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>&lt;&gt;,「」内の文字</string>
			<key>match</key>
			<string>(^|\s)(「|\&lt;).+(」|\&gt;)</string>
			<key>name</key>
			<string>storage</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>ダブルクォーテーション</string>
			<key>match</key>
			<string>".+"</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>シングルクォーテーション内</string>
			<key>match</key>
			<string>\'.+\'</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>{}内の文字</string>
			<key>match</key>
			<string>\{.+\}</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>@+半角スペース以下</string>
			<key>match</key>
			<string>@\s.+</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>http:かhttps:以下</string>
			<key>match</key>
			<string>http(:|s:)\S.*</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>*+半角スペース以下</string>
			<key>match</key>
			<string>\*.+</string>
			<key>name</key>
			<string>meta.tag</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>コメントアウト</string>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>/**/内の文字(ブロックコメントアウト)改行までどう含めるかが課題</string>
			<key>match</key>
			<string>\/\*.*</string>
			<key>name</key>
			<string>source comment.block</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.enhanced</string>
</dict>
</plist>
