<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>Enhanced text</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>__以下</string>
			<key>match</key>
			<string>^\_{2}(\s|\_|.)*</string>
			<key>name</key>
			<string>meta.package</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>--以下(Markdownのライン)</string>
			<key>match</key>
			<string>^\-{2}(\s|\-|.)*</string>
			<key>name</key>
			<string>entity.name.type</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>行頭の*か+か-(Markdownの項目)</string>
			<key>match</key>
			<string>(^|\s)(((\*|\+|\-)\s)|・)</string>
			<key>name</key>
			<string>keyword.control.import</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>カッコ内の数字</string>
			<key>match</key>
			<string>\((\d|\.|\-)+\)</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>行頭のカッコ内の英字1文字</string>
			<key>match</key>
			<string>(^|\s)\(\w\)</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>行頭にある数字とドット(Markdownの数字項目)</string>
			<key>match</key>
			<string>(\s|^)\d+\.\s</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>&lt;&gt;内</string>
			<key>match</key>
			<string>\&lt;+[^\&gt;]+\&gt;+</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>&lt;&gt;内</string>
			<key>match</key>
			<string>＜+[^＞]+＞+</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>「」内</string>
			<key>match</key>
			<string>「[^」]*」</string>
			<key>name</key>
			<string>storage</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>飾りカッコ【】内</string>
			<key>match</key>
			<string>【[^】]*】</string>
			<key>name</key>
			<string>storage</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>[]内</string>
			<key>match</key>
			<string>\[+[^\]]+\]+</string>
			<key>name</key>
			<string>keyword.control.import</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>ダブルクォーテーション内</string>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>シングルクォーテーション内</string>
			<key>match</key>
			<string>\'[^\']*\'</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>&lt;スペース&gt;**文字**&lt;スペース&gt;(Markdownの太字)</string>
			<key>match</key>
			<string>(^|\s)\*{2}[^(\*{2})]*\*{2}($|\s)</string>
			<key>name</key>
			<string>punctuation.definition.string.begin</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>&lt;スペース&gt;*文字*&lt;スペース&gt;(Markdownのイタリック体)</string>
			<key>match</key>
			<string>(^|\s)\*[^(\*)]*\*($|\s)</string>
			<key>name</key>
			<string>support.type</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>~~&lt;スペース&gt;文字&lt;スペース&gt;~~(Markdownの打ち消し文字)</string>
			<key>match</key>
			<string>(~~)[^(~~)]*(~~)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>バッククォート内(Markdownのコード)</string>
			<key>match</key>
			<string>`[^`]*(\s|\`|.)</string>
			<key>name</key>
			<string>meta.diff.header</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>行頭の&gt;</string>
			<key>match</key>
			<string>^\&gt;</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>直前に]がある()内の文字列  ただし]は含まない  (MarkdownのURL)</string>
			<key>match</key>
			<string>(?&lt;=\])(\(.*\))</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>行頭のhttp:かhttps:以下</string>
			<key>match</key>
			<string>(^|\s)http(:|s:)\S+</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>#一個以上と半角スペース以下(Markdownの見出し)</string>
			<key>match</key>
			<string>\#+\s.+</string>
			<key>name</key>
			<string>meta.tag</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>@ 半角スペース 半角スペース以外の文字にマッチ、末尾がスペース2つ以上</string>
			<key>match</key>
			<string>(@|＠)\s.*\S(\s{3,})$</string>
			<key>name</key>
			<string>constant.character.escaped</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>コメントアウト</string>
			<key>match</key>
			<string>//\s.*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.enhanced</string>
</dict>
</plist>
